pipeCacheDuration: 5000 #ms
transferCooldown: 20 #ticks
dispenserRecipe:
  IRON_BLOCK: 1
  DISPENSER: 1
  HOPPER: 1
dropperRecipe:
  IRON_BLOCK: 1
  DROPPER: 1
  HOPPER: 1
chunkLoaderRecipe:
  FURNACE: 1
  OBSIDIAN: 1
  GOLD_BLOCK: 1
maxPipeLength: 128
maxPipeOutputs: 64
gui:
  enabled: "WOOL:5"
  disabled: "WOOL:14"
  filler: "STAINED_GLASS_PANE:15"
