pipeCacheDuration: 10000 #ms
transferCooldown: 20 #ticks
dispenserRecipe:
  IRON_BLOCK: 1
  DISPENSER: 1
  HOPPER: 1
dropperRecipe:
  IRON_BLOCK: 1
  DROPPER: 1
  HOPPER: 1
chunkLoaderRecipe:
  BEACON: 1
  OBSIDIAN: 1
  GOLD_BLOCK: 1

