pipeCacheDuration: 600 #s
pipeCacheSize: 1000 #number of cached inputs
transferCooldown: 20 #ticks
pistonUpdateCheck: true
dispenserRecipe:
  IRON_BLOCK: 1
  DISPENSER: 1
  HOPPER: 1
dropperRecipe:
  IRON_BLOCK: 1
  DROPPER: 1
  HOPPER: 1
chunkLoaderRecipe:
  FURNACE: 1
  OBSIDIAN: 1
  GOLD_BLOCK: 1
maxPipeLength: 128
maxPipeOutputs: 64
gui:
  true: "WOOL:5"
  false: "WOOL:14"
  filler: "STAINED_GLASS_PANE:15"
  copy: "BOOK_AND_QUILL"
