name: Pipes
version: '${minecraft.plugin.version}'
main: io.github.apfelcreme.Pipes.Pipes
author: Lord36
commands:
   pipe:
      description: Creating and inspecting Pipes
      usage: /pipe <info>
      permission:
      permission-message:
permissions:
  Pipes.*:
    description: All
    children:
      Pipes.mod: true
      Pipes.user: true
  Pipes.mod:
    description: all mod permissions
    children:
      Pipes.detect: true
      Pipes.monitor: true
      Pipes.placeChunkLoader: true
      Pipes.reload: true
      Pipes.tp: true
  Pipes.user:
    description: package of all user permissions
    children:
      Pipes.info: true
  Pipes.detect:
    description: detect all ongoing transfers for a given period of time
  Pipes.info:
    description: check a dispenser
  Pipes.monitor:
    description: show the current plugin status
  Pipes.placeChunkLoader:
    description: place a furnace to work as a chunk loader
  Pipes.reload:
    description: reload the configs
  Pipes.tp:
    description: teleport to the dispenserLocation of a detection result