name: Pipes
version: '${minecraft.plugin.version}'
main: io.github.apfelcreme.Pipes.Pipes
author: Lord36
authors: [Phoenix616]
api-version: '1.13'
softdepend: [BlockInfoStorage]
commands:
   pipe:
      description: Creating and inspecting Pipes
      usage: /pipe <info>
      permission:
      permission-message:
permissions:
  Pipes.*:
    description: All
    children:
      Pipes.admin: true
      Pipes.mod: true
      Pipes.user: true
  Pipes.admin:
    description: all admin permissions
    children:
      Pipes.placeChunkLoader: true
      Pipes.reload: true
      Pipes.get: true
  Pipes.mod:
    description: all mod permissions
    children:
      Pipes.detect: true
      Pipes.monitor: true
      Pipes.tp: true
  Pipes.user:
    description: package of all user permissions
    children:
      Pipes.info: true
      Pipes.applybook: true
  Pipes.detect:
    description: detect all ongoing transfers for a given period of time
  Pipes.get:
    description: get pipes items
  Pipes.info:
    description: check a dispenser
  Pipes.monitor:
    description: show the current plugin status
  Pipes.placeChunkLoader:
    description: place a furnace to work as a chunk loader
  Pipes.reload:
    description: reload the configs
  Pipes.tp:
    description: teleport to the location of the input of a pipe from a detection result
  Pipes.applybook:
    description: allows to apply settings via sneaking and left clicking a pipe part with a book